#! /bin/sh

# Launch polybar
$HOME/.config/polybar/launch.sh

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config normal_border_color '#263238'
bspc config focused_border_color '#455a64'
bspc config active_border_color '#263238'

bspc config window_gap           25

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config top_padding 10

bspc config automatic_scheme alternate
bspc config pointer_modifier mod4

bspc rule -a Vlc follow=on state=floating
bspc rule -a Lollypop desktop='^1' follow=on
bspc rule -a Spotify desktop='^1' follow=on
bspc rule -a TelegramDesktop desktop='^1' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Gnome-system-monitor state=floating
bspc rule -a Gnome-control-center state=floating
bspc rule -a MenuLibre state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a QjackCtl state=floating
bspc rule -a "Ardour-5.12.0" desktop='^10' state=floating
bspc rule -a "Ulauncher" state=floating
