#! /bin/sh

export BSPWM=true

sxhkd &
setxkbmap -layout latam

# Walpaper and shell colors setter
# $HOME/.scripts/pywal-random-bg-loop.sh &

wal -n -i /media/Datos/Agustín/Imágenes/Ultrawide
feh --bg-tile "$(< "${HOME}/.cache/wal/wal")"

# Launch polybar
# $HOME/.config/polybar/launch.sh

# Launch compton
$HOME/.config/compton/launch.sh


# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
